name: scolors
version: 1.0.0

description: A colors playful dependency.
repository: https://github.com/smith8h/scolors-flutter

topics:
  - colors
  - dart
  - tools

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
